/**
 * Streaming CSV reader.
 *
 * The export files run to 100+ MB each, so nothing here ever materialises a
 * whole file as a string: we pull chunks off the file's stream, decode them
 * incrementally and hand out one line at a time, carrying any partial trailing
 * line into the next chunk.
 *
 * The format is generated by a data warehouse and contains no quoting or
 * escaping at all, so splitting on commas is safe.
 */

import type { FileLike } from '../schema/streams';

export interface LineReaderOptions {
	/** Called roughly every `progressEveryBytes` with the running byte count. */
	onProgress?: (bytesRead: number) => void;
	progressEveryBytes?: number;
}

/**
 * Yields the file's lines. A UTF-8 BOM on the first line is stripped —
 * every export file carries one, and it would otherwise corrupt the first
 * header name into `﻿vin`.
 */
export async function* readLines(
	file: FileLike,
	options: LineReaderOptions = {}
): AsyncGenerator<string, void, undefined> {
	const { onProgress, progressEveryBytes = 8 * 1024 * 1024 } = options;
	const reader = file.stream().getReader();
	const decoder = new TextDecoder('utf-8');
	let carry = '';
	let bytesRead = 0;
	let sinceProgress = 0;
	let atStart = true;

	try {
		for (;;) {
			const { done, value } = await reader.read();
			if (done) break;

			bytesRead += value.byteLength;
			sinceProgress += value.byteLength;

			let text = decoder.decode(value, { stream: true });
			if (atStart) {
				if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
				atStart = false;
			}

			carry += text;
			let start = 0;
			for (;;) {
				const nl = carry.indexOf('\n', start);
				if (nl === -1) break;
				let line = carry.slice(start, nl);
				// Tolerate CRLF even though these exports use bare LF.
				if (line.endsWith('\r')) line = line.slice(0, -1);
				if (line.length) yield line;
				start = nl + 1;
			}
			carry = start ? carry.slice(start) : carry;

			if (onProgress && sinceProgress >= progressEveryBytes) {
				onProgress(bytesRead);
				sinceProgress = 0;
			}
		}

		carry += decoder.decode();
		if (carry.endsWith('\r')) carry = carry.slice(0, -1);
		if (carry.length) yield carry;
		onProgress?.(bytesRead);
	} finally {
		reader.releaseLock();
	}
}

/** Splits a header line into trimmed, lower-cased column names. */
export function parseHeader(line: string): string[] {
	return line.split(',').map((name) => name.trim().toLowerCase());
}

/**
 * Parses a numeric field. Empty fields are the export's null token and become
 * NaN. Values arrive as floats even for enums ("4.0"), so everything goes
 * through parseFloat.
 */
export function parseField(field: string): number {
	if (field.length === 0) return NaN;
	return parseFloat(field);
}
